server:
  port: 8083

spring:
  application:
    name: model-proxy-service

langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY:demo}
      model-name: gpt-3.5-turbo
      temperature: 0.7
  dashscope:
    api-key: ${DASHSCOPE_API_KEY:demo}
    chat-model:
      model-name: deepseek-v3.2
      temperature: 0.7
